### ISSUE TITLE
SliceSequenceConverter error

### ISSUE THREAD

**Issue by Mqrry** [radioegor146/bss2css#1]
Exception in thread "main" java.lang.RuntimeException: Converter 'com.sun.javafx.scene.layout.region.SliceSequenceConverter' not found (contact author and create issue on github with class name)
        at by.radioegor146.Main.lambda$null$24(Main.java:534)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at by.radioegor146.Main.lambda$main$25(Main.java:524)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
        at by.radioegor146.Main.main(Main.java:495)

**Comment by radioegor146** [comment]
Can you give BSS that caused error?

**Comment by radioegor146** [comment]
fixed in e628133

**Comment by radioegor146** [comment]
fixed in 4c8c737
