### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/paint/Color

### ISSUE THREAD

**Issue by HardMode2015** [radioegor146/bss2css#2]
hello,

how i can fix this error

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/paint/Color
        at by.radioegor146.Main.<clinit>(Main.java:431)
Caused by: java.lang.ClassNotFoundException: javafx.scene.paint.Color
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more
```

**Comment by radioegor146** [comment]
You need to install OpenJFX as a dependency to make this work

**Comment by HardMode2015** [comment]
> You need to install OpenJFX as a dependency to make this work

can you explain how to use please
